### PR TITLE
Separated css from html files

### PR DESCRIPTION
**Pull request by naomileron**
Some html files had the css in a style tag -- all css now appears in its own .css file

### CODE REVIEW

**Review by racheldewolfe — COMMENTED** [review]
are first main and main the same css? If so they can share the same css file.

**Comment by naomileron** [comment]
> are first main and main the same css? If so they can share the same css file.

Oh yeah that's true. I'll change that then

**Review by racheldewolfe — COMMENTED** [review]
assuming accounts is holding the css for main and firstMain? the naming doesn't make the most sense though considering the name of the other two pages, could we name it main maybe?

**Comment by naomileron** [comment]
> assuming accounts is holding the css for main and firstMain? the naming doesn't make the most sense though considering the name of the other two pages, could we name it main maybe?

Alright I'll change that

**Review by racheldewolfe — APPROVED** [review]
Looks good!

**Pull request merged**
